require_relative '../lib/gem-find'
require_relative '../lib/gem-find/cli'
require_relative '../lib/gem-find/search_rubygems'
require_relative '../lib/gem-find/version'
require_relative '../lib/gem-find/found_gem.rb'

require 'open-uri'
require 'nokogiri'
require 'pry'
require 'json'
require 'rspec'