require_relative '../lib/gem_exist'
require_relative '../lib/gem_exist/cli'
require_relative '../lib/gem_exist/search_rubygems'
require_relative '../lib/gem_exist/version'
require_relative '../lib/gem_exist/found_gem.rb'

require 'open-uri'
require 'nokogiri'
require 'pry'
require 'json'
require 'rspec'